### ISSUE TITLE
Замена стандартного Server Name

### ISSUE THREAD

**Issue by partymaker-py** [Tinkoff/sage-community#1]
Добрый день!

Установил Sage согласно инструкции, исходные данные:
- ОС: Debian 10
- Docker: 24.0.2

По итогу все контейнеры запустились
![image](https://github.com/Tinkoff/sage-community/assets/74206574/ec9e91ba-84cd-4eb2-ad20-108137890dcb)

При попытке подключиться к UI интерфейсу с другой машины, получаем ошибку
![image](https://github.com/Tinkoff/sage-community/assets/74206574/3df02d59-8948-4f28-84e3-03c106545f80)

При этом, если обращаться по имени 10.102.0.1.nip.io (предварительно прописав его в файле hosts), то все работает нормально. Попытки изменить headers (host) и server_name вручную успехом не увенчались. Ошибка осталась прежней. Было бы здорово, если бы server_name выбирался изначально правильный, ну или хотя бы по IP сервис был доступен. 

Заранее спасибо!

**Comment by a-merson** [comment]
Реализовали возможность задать хост с помощью ключа hostname:
```sh
  ./sage-community.sh install --hostname <your-domain-name>
  ```
Необходимое условие: `<your-domain-name>` а) должен резолвиться и б) должен резолвиться не в 127.0.0.1
